services:
    zotero-pdf2zh:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - ZOTERO_PDF2ZH_FROM_IMAGE=byaidu/pdf2zh:1.9.6
                - ZOTERO_PDF2ZH_SERVER_FILE_DOWNLOAD_URL=https://raw.githubusercontent.com/guaguastandup/zotero-pdf2zh/refs/tags/v2.3.5/server.py
        container_name: zotero-pdf2zh
        restart: unless-stopped
        ports:
            - 8888:8888
        environment:
            - TZ=Asia/Shanghai
            - HF_ENDPOINT=https://hf-mirror.com
        volumes:
            - ./shared/translated:/app/translated
            - ./shared/config.json:/app/config.json
            # - ./shared/LXGWWenKai-Regular.ttf:/app/LXGWWenKai-Regular.ttf
        depends_on:
            - config-manager

    config-manager:
        build:
            context: .
            dockerfile: Dockerfile.config-manager
        container_name: zotero-pdf2zh-config-manager
        restart: unless-stopped
        ports:
            - 8889:8889
        environment:
            - TZ=Asia/Shanghai
            - CONFIG_PATH=/config/config.json
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=admin123
            - SECRET_KEY=change_this_in_production_to_random_string
        volumes:
            - ./shared:/config
